title: Pixel++
description: A programming language for efficient manipulation of images
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-gist
github:
  zip_url: https://github.com/maobowen/PixelPlusPlus/zipball/master
  tar_url: https://github.com/maobowen/PixelPlusPlus/tarball/master
